@extends('home.base')
@section('home-content')
<!-- Home Section Starts -->
<section class="home-2" style="background-image: url('{{ asset('home/img/banner.png')}}');">
    <div class="container">
       <div class="home-2-head">
          <p>great reports</p>
       </div>
       <div class="home-2-img" style="background-image:url('{{asset('home/img/great-reports-1.png')}}');">

       </div>
    </div>
 </section>
 <!-- Home Section Ends -->

 <!-- Social Network Section Starts -->
 <section class="social-networks-2 bg-white">
    <div class="container">
       <div class="social-networks-item">
          <div class="social-networks-item-img">
             <img src="{{asset('home/img/great-reports-2.png')}}" alt="Great Reports" />
          </div>
          <div class="social-networks-item-text">
             <div class="social-networks-item-text-head">
                <p>Easy to understand</p>
             </div>
             <div class="social-networks-item-text-desc">
                <p>Reports generated by socialcalabash are simplified and easy to understand. We keep things simple so you can can see what works and what does not.</p>
             </div>
          </div>
       </div>
    </div>
 </section>
 <section class="social-networks-2">
    <div class="container">
       <div class="social-networks-item">
          <div class="social-networks-item-text">
             <div class="social-networks-item-text-head">
                <p>White labelled</p>
             </div>
             <div class="social-networks-item-text-desc">
                <p>Depending on the type of plan you are subscribed to, you can now offer reports that are branded with your agency details so that your customers only see you.</p>
             </div>
          </div>
          <div class="social-networks-item-img">
             <img src="{{asset('home/img/great-reports-3.png')}}" alt="Great Reports" />
          </div>
       </div>
    </div>
 </section>
 <section class="social-networks-2 bg-white">
    <div class="container">
       <div class="social-networks-item">
          <div class="social-networks-item-img">
             <img src="{{asset('home/img/great-reports-4.png')}}" alt="Great Reports" />
          </div>
          <div class="social-networks-item-text">
             <div class="social-networks-item-text-head">
                <p>Save as PDF</p>
             </div>
             <div class="social-networks-item-text-desc">
                <p>Your reports can now be saved as a PDF so that you can forward on to your clients easily.</p>
             </div>
          </div>
       </div>
    </div>
 </section>
 <!-- Socail Network Section Ends -->
@endsection
